spring.application.name=demo

# Configuración de la base de datos (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MantenimientoCliente;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Coloca aquí las credenciales que habilitaste
spring.datasource.username=sa
spring.datasource.password=12345678

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# Puerto
server.port=8080